"""
Constants definition module containing various constants and configuration
parameters used in the project.
"""

import os

# env
Env = os.getenv("ENVIRONMENT")
ENV_PRODUCTION = "production"
ENV_PRERELEASE = "prerelease"
ENV_DEVELOPMENT = "development"

# service info
SERVICE_SUB_KEY = "SERVICE_SUB"
SERVICE_NAME_KEY = "SERVICE_NAME"
SERVICE_LOCATION_KEY = "SERVICE_LOCATION"
SERVICE_PORT_KEY = "SERVICE_PORT"
SERVICE_APP_KEY = "SERVICE_APP"

# const
IMAGE_GENERATE_MAX_PROMPT_LEN = 510

# otlp info
OTLP_ENABLE_KEY = "OTLP_ENABLE"
OTLP_DC_KEY = "OTLP_DC"
OTLP_SERVICE_NAME_KEY = "OTLP_SERVICE_NAME"
KAFKA_TOPIC_KEY = "KAFKA_TOPIC"

OTLP_ENDPOINT_KEY = "OTLP_ENDPOINT"
OTLP_METRIC_EXPORT_INTERVAL_MILLIS_KEY = "OTLP_METRIC_EXPORT_INTERVAL_MILLIS"
OTLP_METRIC_EXPORT_TIMEOUT_MILLIS_KEY = "OTLP_METRIC_EXPORT_TIMEOUT_MILLIS"
OTLP_METRIC_TIMEOUT_KEY = "OTLP_METRIC_TIMEOUT"
OTLP_TRACE_TIMEOUT_KEY = "OTLP_TRACE_TIMEOUT"
OTLP_TRACE_MAX_QUEUE_SIZE_KEY = "OTLP_TRACE_MAX_QUEUE_SIZE"
OTLP_TRACE_SCHEDULE_DELAY_MILLIS_KEY = "OTLP_TRACE_SCHEDULE_DELAY_MILLIS"
OTLP_TRACE_MAX_EXPORT_BATCH_SIZE_KEY = "OTLP_TRACE_MAX_EXPORT_BATCH_SIZE"
OTLP_TRACE_EXPORT_TIMEOUT_MILLIS_KEY = "OTLP_TRACE_EXPORT_TIMEOUT_MILLIS"
KAFKA_SERVERS_KEY = "KAFKA_SERVERS"
KAFKA_TIMEOUT_KEY = "KAFKA_TIMEOUT"
